-- Generated by infrastructure/tools/gen-hook-targets.js. Do not edit by hand.
return {
  { type = "Verse.GenMath", method = "PositiveMod", sig = "int,int", from = "tests/smoke/Lua/main.lua" },
  { type = "Verse.GenText", method = "CapitalizeFirst", sig = "string", from = "tests/smoke/Lua/main.lua" },
  { type = "Verse.Pawn", method = "Tick", sig = "", from = "tests/smoke/Lua/main.lua" },
  { type = "Verse.Pawn", method = "TickInterval", sig = "", from = "tests/smoke/Lua/main.lua" },
}
