-- Ecosystem checks that need no game: interop, the test framework with mocks, the profiler, debug actions.
local t = game.test

t.describe("interop", function()
  t.it("publishes and resolves with version ranges", function()
    game.interop.publish("eco.math", "1.4.2", { double = function(x) return x * 2 end })
    t.expect(game.interop.has("eco.math")).to_be(true)
    t.expect(game.interop.has("eco.math", "^1.2")).to_be(true)
    t.expect(game.interop.has("eco.math", "^2.0")).to_be(false)
    t.expect(game.interop.has("eco.math", ">=1.4.2")).to_be(true)
    t.expect(game.interop.has("eco.math", "~1.3")).to_be(false)
    t.expect(game.interop.has("eco.math", "1.4.2")).to_be(true)
    local ok, res = game.interop.call("eco.math", "double", 21)
    t.expect(ok).to_be(true)
    t.expect(res).to_be(42)
  end)
  t.it("a missing mod is a plain false", function()
    local ok = game.interop.call("eco.nothing", "x")
    t.expect(ok).to_be(false)
    local api, why = game.interop.get("eco.nothing")
    t.expect(api).to_be_nil()
    t.expect(why).to_contain("not published")
  end)
  t.it("when runs now or after the publish", function()
    local seen = 0
    game.interop.when("eco.late", "^1", function(api) seen = seen + api.n end)
    t.expect(seen).to_be(0)
    game.interop.publish("eco.late", "1.0.0", { n = 5 })
    t.expect(seen).to_be(5)
    game.interop.when("eco.late", "^1", function(api) seen = seen + api.n end)
    t.expect(seen).to_be(10)
  end)
  t.it("rejects bad input", function()
    t.expect(function() game.interop.publish("x", "nope", {}) end).to_error("RK1001")
    t.expect(function() game.interop.publish("", "1.0", {}) end).to_error("RK1001")
  end)
end)

t.describe("mock host", function()
  t.it("answers ops with the mock and records calls", function()
    t.mock("pawn.skills", function(a) return { { def = "Shooting", level = 7 } } end)
    local skills = game.pawns.skills(9)
    t.expect(skills[1].level).to_be(7)
    t.expect(#t.calls("pawn.skills")).to_be(1)
    t.expect(t.calls("pawn.skills")[1].args.h).to_be(9)
  end)
  t.it("a mock can raise an RK error", function()
    t.mock("pawn.skills", function() error("RK2001: pawn handle is stale or null") end)
    t.expect(function() game.pawns.skills(9) end).to_error("RK2001")
  end)
  t.it("unmocked ops answer nil instead of reaching a game", function()
    t.expect(game.time.now()).to_be_nil()
  end)
end)

t.describe("framework", function()
  t.it("deep equality and containment", function()
    t.expect({ a = { 1, 2 } }).to_equal({ a = { 1, 2 } })
    t.expect({ 1, 2, 3 }).to_contain(2)
    t.expect("hello").to_contain("ell")
    t.expect({ 1, 2 }).to_have_length(2)
    t.expect(0.1 + 0.2).to_be_close(0.3, 1e-9)
  end)
  t.it("events reach handlers", function()
    local got
    game.events.on("pawn.died", function(p) got = p.tag end)
    t.emit("pawn.died", { tag = "x" })
    t.expect(got).to_be("x")
  end)
end)

t.describe("dev", function()
  t.it("debug actions register and run", function()
    local ran = false
    game.dev.action("eco.act", function() ran = true end, "test action")
    t.expect(#game.dev.actions()).to_be(1)
    t.expect(game.dev.run("eco.act")).to_be(true)
    t.expect(ran).to_be(true)
    t.expect(function() game.dev.run("eco.none") end).to_error("RK3001")
  end)
  t.it("the profiler reports and resets", function()
    t.tick(3)
    local rows = game.profiler.report()
    t.expect(type(rows)).to_be("table")
    game.profiler.reset()
    t.expect(#game.profiler.report()).to_be(0)
  end)
  t.it("eval works in test mode", function()
    local ok, text = game.dev.eval("1 + 2")
    t.expect(ok).to_be(true)
    t.expect(text).to_be("3")
  end)
end)

t.describe("strict mocks", function()
  t.it("rejects a mock for an op the host does not have", function()
    t.expect(function() t.mock("pawn.set_draftd", true) end).to_error("RK1001")
    t.mock("pawn.set_drafted", true)
  end)
  t.it("rejects a wrong argument type", function()
    t.expect(function() game.maps.set_roof(5, "x", 4) end).to_error("RK1001")
  end)
  t.it("rejects a missing required argument", function()
    t.expect(function() game.maps.set_roof(5, 3) end).to_error("RK1001")
  end)
  t.it("rejects extra arguments", function()
    t.expect(function() game.pawns.kinds(1, 2, 3) end).to_error("RK1001")
  end)
  t.it("accepts a wrapped object or a handle as the subject", function()
    t.mock("pawn.drafted", true)
    t.expect(game.pawns.drafted(7)).to_be(true)
    t.expect(game.pawns.drafted(rim.wrap(7))).to_be(true)
  end)
end)

t.expect(t.run()).to_be(0)
