// Generated by infrastructure/tools/gen-lua-classes.js from src/api/classes.cls. Do not edit by hand.
using System;
using System.Collections.Generic;
using System.Linq;
using RimWorld;
using RimWorld.QuestGen;
using RimWorld.Planet;
using UnityEngine;
using Verse;
using Verse.AI;
using Verse.AI.Group;

namespace RimKit
{
    public class CompProperties_Lua : CompProperties
    {
        public string luaClass;

        public CompProperties_Lua()
        {
            compClass = typeof(ThingComp_Lua);
        }
    }

    // Lua family "comp". Register functions with game.classes.define("comp", name, { ... }).
    public class ThingComp_Lua : ThingComp
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("comp", ((CompProperties_Lua)props).luaClass, fn, a);

        public Dictionary<string, string> luaData = new Dictionary<string, string>();
        public override void PostExposeData() { base.PostExposeData(); Scribe_Collections.Look(ref luaData, "luaData", LookMode.Value, LookMode.Value); if (luaData == null) luaData = new Dictionary<string, string>(); }

        public override void PostSpawnSetup(bool respawningAfterLoad)
        {
            base.PostSpawnSetup(respawningAfterLoad);
            L("spawn", parent, respawningAfterLoad);
        }
        public override void CompTick()
        {
            base.CompTick();
            L("tick", parent);
        }
        public override void CompTickRare()
        {
            base.CompTickRare();
            L("tick_rare", parent);
        }
        public override void CompTickLong()
        {
            base.CompTickLong();
            L("tick_long", parent);
        }
        public override string CompInspectStringExtra()
        {
            object r = L("inspect_string", parent);
            return LuaClasses.Str(r, null);
        }
        public override void PostDestroy(DestroyMode mode, Map previousMap)
        {
            base.PostDestroy(mode, previousMap);
            L("destroyed", parent, mode.ToString());
        }
        public override void PostDeSpawn(Map map, DestroyMode mode)
        {
            base.PostDeSpawn(map, mode);
            L("despawned", parent);
        }
    }

    public class HediffCompProperties_Lua : HediffCompProperties
    {
        public string luaClass;

        public HediffCompProperties_Lua()
        {
            compClass = typeof(HediffComp_Lua);
        }
    }

    // Lua family "hediff_comp". Register functions with game.classes.define("hediff_comp", name, { ... }).
    public class HediffComp_Lua : HediffComp
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("hediff_comp", ((HediffCompProperties_Lua)props).luaClass, fn, a);

        public override string CompTipStringExtra => LuaClasses.Str(L("tip", parent.pawn, parent), null);

        public override void CompPostPostAdd(DamageInfo? dinfo)
        {
            base.CompPostPostAdd(dinfo);
            L("post_add", parent.pawn, parent);
        }
        public override void CompPostTick(ref float severityAdjustment)
        {
            base.CompPostTick(ref severityAdjustment);
            L("tick", parent.pawn, parent);
        }
        public override void CompPostPostRemoved()
        {
            base.CompPostPostRemoved();
            L("post_removed", parent.pawn, parent);
        }
    }

    // Lua family "incident". Register functions with game.classes.define("incident", name, { ... }).
    public class IncidentWorker_Lua : IncidentWorker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("incident", LuaClasses.OfDef(def), fn, a);

        protected override bool CanFireNowSub(IncidentParms parms)
        {
            object r = L("can_fire", LuaClasses.Parms(parms));
            return LuaClasses.IsBool(r) ? (bool)r : base.CanFireNowSub(parms);
        }
        protected override bool TryExecuteWorker(IncidentParms parms)
        {
            object r = L("execute", LuaClasses.Parms(parms));
            return LuaClasses.IsBool(r) ? (bool)r : base.TryExecuteWorker(parms);
        }
    }

    // Lua family "condition". Register functions with game.classes.define("condition", name, { ... }).
    public class GameCondition_Lua : GameCondition
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("condition", LuaClasses.OfDef(def), fn, a);

        public override void Init()
        {
            base.Init();
            L("start", SingleMap);
        }
        public override void GameConditionTick()
        {
            base.GameConditionTick();
            L("tick", SingleMap);
        }
        public override void End()
        {
            base.End();
            L("stop", SingleMap);
        }
        public override float TemperatureOffset()
        {
            object r = L("temperature_offset", SingleMap);
            return LuaClasses.IsNumber(r) ? LuaClasses.Float(r, 0f) : base.TemperatureOffset();
        }
    }

    public class StorytellerCompProperties_Lua : StorytellerCompProperties
    {
        public string luaClass;

        public StorytellerCompProperties_Lua()
        {
            compClass = typeof(StorytellerComp_Lua);
        }
    }

    // Lua family "storyteller". Register functions with game.classes.define("storyteller", name, { ... }).
    public class StorytellerComp_Lua : StorytellerComp
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("storyteller", ((StorytellerCompProperties_Lua)props).luaClass, fn, a);

        public override IEnumerable<FiringIncident> MakeIntervalIncidents(IIncidentTarget target) { object r = L("incidents", target as Map, Find.TickManager.TicksGame); if (!(r is List<object> list)) yield break; foreach (object o in list) { var d = Json.AsObject(o); if (d == null) continue; IncidentDef def = DefDatabase<IncidentDef>.GetNamedSilentFail(Json.GetString(d, "incident")); if (def == null) continue; IncidentParms parms = StorytellerUtility.DefaultParmsNow(def.category, target); if (d.ContainsKey("points")) parms.points = Convert.ToSingle(d["points"], System.Globalization.CultureInfo.InvariantCulture); yield return new FiringIncident(def, this, parms); } }

    }

    // Lua family "stat_part". Register functions with game.classes.define("stat_part", name, { ... }).
    public class StatPart_Lua : StatPart
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("stat_part", luaClass, fn, a);

        public string luaClass;
        public override void TransformValue(StatRequest req, ref float val) { object r = L("transform", req.Thing, val, parentStat != null ? parentStat.defName : null); if (LuaClasses.IsNumber(r)) val = LuaClasses.Float(r, val); }
        public override string ExplanationPart(StatRequest req) { return LuaClasses.Str(L("explain", req.Thing, parentStat != null ? parentStat.defName : null), null); }

    }

    // Lua family "stat_worker". Register functions with game.classes.define("stat_worker", name, { ... }).
    public class StatWorker_Lua : StatWorker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("stat_worker", LuaClasses.OfDef(stat), fn, a);

        public override float GetValueUnfinalized(StatRequest req, bool applyPostProcess = true) { object r = L("value", req.Thing, stat.defName); return LuaClasses.IsNumber(r) ? LuaClasses.Float(r, 0f) : base.GetValueUnfinalized(req, applyPostProcess); }

    }

    // Lua family "work_giver". Register functions with game.classes.define("work_giver", name, { ... }).
    public class WorkGiver_Lua : WorkGiver_Scanner
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("work_giver", LuaClasses.OfDef(def), fn, a);

        public override ThingRequest PotentialWorkThingRequest { get { string g = LuaClasses.Str(L("request_group"), null); return !string.IsNullOrEmpty(g) && Enum.TryParse(g, true, out ThingRequestGroup group) ? ThingRequest.ForGroup(group) : ThingRequest.ForGroup(ThingRequestGroup.Undefined); } }
        public override IEnumerable<Thing> PotentialWorkThingsGlobal(Pawn pawn) { object r = L("potential", pawn); return r == null ? base.PotentialWorkThingsGlobal(pawn) : LuaClasses.Things<Thing>(r); }

        public override bool HasJobOnThing(Pawn pawn, Thing t, bool forced)
        {
            object r = L("has_job", pawn, t, forced);
            return LuaClasses.IsBool(r) ? (bool)r : false;
        }
        public override Job JobOnThing(Pawn pawn, Thing t, bool forced)
        {
            object r = L("job", pawn, t, forced);
            Job job = LuaClasses.MakeJob(r);
            return job ?? null;
        }
        public override bool ShouldSkip(Pawn pawn, bool forced)
        {
            object r = L("skip", pawn, forced);
            return LuaClasses.IsBool(r) ? (bool)r : base.ShouldSkip(pawn, forced);
        }
    }

    // Lua family "job_giver". Register functions with game.classes.define("job_giver", name, { ... }).
    public class JobGiver_Lua : ThinkNode_JobGiver
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("job_giver", luaClass, fn, a);

        public string luaClass;

        protected override Job TryGiveJob(Pawn pawn)
        {
            object r = L("job", pawn);
            Job job = LuaClasses.MakeJob(r);
            return job ?? null;
        }
    }

    // Lua family "place_worker". Register functions with game.classes.define("place_worker", name, { ... }).
    public class PlaceWorker_Lua : PlaceWorker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("place_worker", null, fn, a);

        public override AcceptanceReport AllowsPlacing(BuildableDef checkingDef, IntVec3 loc, Rot4 rot, Map map, Thing thingToIgnore = null, Thing thing = null) { string cls = LuaClasses.OfDef(checkingDef); object r = LuaClasses.Call("place_worker", cls, "allows", checkingDef.defName, loc.x, loc.z, rot.AsInt, map); return LuaClasses.Report(r, true); }

    }

    // Lua family "recipe_worker". Register functions with game.classes.define("recipe_worker", name, { ... }).
    public class RecipeWorker_Lua : RecipeWorker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("recipe_worker", LuaClasses.OfDef(recipe), fn, a);

        public override void ApplyOnPawn(Pawn pawn, BodyPartRecord part, Pawn billDoer, List<Thing> ingredients, Bill bill)
        {
            base.ApplyOnPawn(pawn, part, billDoer, ingredients, bill);
            L("apply", pawn, billDoer, part != null ? part.Index : -1);
        }
    }

    // Lua family "thought_worker". Register functions with game.classes.define("thought_worker", name, { ... }).
    public class ThoughtWorker_Lua : ThoughtWorker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("thought_worker", LuaClasses.OfDef(def), fn, a);

        protected override ThoughtState CurrentStateInternal(Pawn p) { object r = L("state", p); if (r is bool b) return b ? ThoughtState.ActiveAtStage(0) : ThoughtState.Inactive; if (LuaClasses.IsNumber(r)) return ThoughtState.ActiveAtStage(Math.Max(0, LuaClasses.Int(r, 0))); return ThoughtState.Inactive; }
        protected override ThoughtState CurrentSocialStateInternal(Pawn p, Pawn otherPawn) { object r = L("social_state", p, otherPawn); if (r is bool b) return b ? ThoughtState.ActiveAtStage(0) : ThoughtState.Inactive; if (LuaClasses.IsNumber(r)) return ThoughtState.ActiveAtStage(Math.Max(0, LuaClasses.Int(r, 0))); return ThoughtState.Inactive; }

    }

    // Lua family "mental_state_worker". Register functions with game.classes.define("mental_state_worker", name, { ... }).
    public class MentalStateWorker_Lua : MentalStateWorker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("mental_state_worker", LuaClasses.OfDef(def), fn, a);

        public override bool StateCanOccur(Pawn pawn)
        {
            object r = L("can_occur", pawn);
            return LuaClasses.IsBool(r) ? (bool)r : base.StateCanOccur(pawn);
        }
    }

    // Lua family "need". Register functions with game.classes.define("need", name, { ... }).
    public class Need_Lua : Need
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("need", LuaClasses.OfDef(def), fn, a);

        public Need_Lua(Pawn pawn) : base(pawn)
        {
        }

        public override void NeedInterval() { if (def.fallPerDay > 0f) CurLevel -= def.fallPerDay / 400f; L("interval", pawn, CurLevel); }

    }

    public class CompProperties_AbilityEffect_Lua : CompProperties_AbilityEffect
    {
        public string luaClass;

        public CompProperties_AbilityEffect_Lua()
        {
            compClass = typeof(CompAbilityEffect_Lua);
        }
    }

    // Lua family "ability". Register functions with game.classes.define("ability", name, { ... }).
    public class CompAbilityEffect_Lua : CompAbilityEffect
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("ability", ((CompProperties_AbilityEffect_Lua)props).luaClass, fn, a);

        public override void Apply(LocalTargetInfo target, LocalTargetInfo dest)
        {
            base.Apply(target, dest);
            L("apply", parent.pawn, target.Thing, target.Cell.x, target.Cell.z);
        }
        public override bool Valid(LocalTargetInfo target, bool throwMessages)
        {
            object r = L("valid", parent.pawn, target.Thing);
            return LuaClasses.IsBool(r) ? (bool)r : base.Valid(target, throwMessages);
        }
    }

    // Lua family "damage_worker". Register functions with game.classes.define("damage_worker", name, { ... }).
    public class DamageWorker_Lua : DamageWorker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("damage_worker", LuaClasses.OfDef(def), fn, a);

        public override DamageResult Apply(DamageInfo dinfo, Thing victim) { DamageResult r = base.Apply(dinfo, victim); L("applied", victim, dinfo.Amount, r != null ? r.totalDamageDealt : 0f); return r; }

    }

    // Lua family "projectile". Register functions with game.classes.define("projectile", name, { ... }).
    public class Projectile_Lua : Projectile
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("projectile", LuaClasses.OfDef(def), fn, a);

        protected override void Impact(Thing hitThing, bool blockedByShield = false) { L("impact", this, hitThing, launcher); base.Impact(hitThing, blockedByShield); }

    }

    // Lua family "verb". Register functions with game.classes.define("verb", name, { ... }).
    public class Verb_Lua : Verb_LaunchProjectile
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("verb", LuaClasses.OfDef(EquipmentSource != null ? EquipmentSource.def : null), fn, a);

        protected override bool TryCastShot() { object r = L("shoot", CasterPawn, currentTarget.Thing); return LuaClasses.IsBool(r) ? (bool)r : base.TryCastShot(); }

    }

    // Lua family "gen_step". Register functions with game.classes.define("gen_step", name, { ... }).
    public class GenStep_Lua : GenStep
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("gen_step", LuaClasses.OfDef(def), fn, a);

        public override int SeedPart => 4815162;

        public override void Generate(Map map, GenStepParams parms)
        {
            L("generate", map);
        }
    }

    // Lua family "thing_set_maker". Register functions with game.classes.define("thing_set_maker", name, { ... }).
    public class ThingSetMaker_Lua : ThingSetMaker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("thing_set_maker", luaClass, fn, a);

        public string luaClass;
        protected override bool CanGenerateSub(ThingSetMakerParams parms) { return !LuaClasses.Has("thing_set_maker", luaClass, "can_generate") || LuaClasses.Bool(L("can_generate"), true); }
        protected override void Generate(ThingSetMakerParams parms, List<Thing> outThings) { object r = L("generate", parms.totalMarketValueRange.HasValue ? parms.totalMarketValueRange.Value.max : 0f); if (!(r is List<object> list)) return; foreach (object o in list) { var d = Json.AsObject(o); if (d == null) continue; ThingDef def = DefDatabase<ThingDef>.GetNamedSilentFail(Json.GetString(d, "def")); if (def == null) continue; Thing t = ThingMaker.MakeThing(def, def.MadeFromStuff ? GenStuff.DefaultStuffFor(def) : null); t.stackCount = Math.Max(1, (int)Json.GetLong(d, "count", 1)); outThings.Add(t); } }
        protected override IEnumerable<ThingDef> AllGeneratableThingsDebugSub(ThingSetMakerParams parms) { yield break; }

    }

    // Lua family "quest_part". Register functions with game.classes.define("quest_part", name, { ... }).
    public class QuestPart_Lua : QuestPart
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("quest_part", luaClass, fn, a);

        public string luaClass;
        public string inSignal;
        public override void Notify_QuestSignalReceived(Signal signal) { base.Notify_QuestSignalReceived(signal); if (signal.tag == inSignal) L("signal", quest != null ? quest.id : 0, signal.tag); }
        public override void ExposeData() { base.ExposeData(); Scribe_Values.Look(ref luaClass, "luaClass"); Scribe_Values.Look(ref inSignal, "inSignal"); }

    }

    // Lua family "lord_toil". Register functions with game.classes.define("lord_toil", name, { ... }).
    public class LordToil_Lua : LordToil
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("lord_toil", luaClass, fn, a);

        public string luaClass;
        public LordToil_Lua() { }
        public LordToil_Lua(string cls) { luaClass = cls; }
        public override void UpdateAllDuties() { L("duties", LuaClasses.Handles(lord.ownedPawns.Cast<object>())); }

    }

    // Lua family "gene". Register functions with game.classes.define("gene", name, { ... }).
    public class Gene_Lua : Gene
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("gene", LuaClasses.OfDef(def), fn, a);

        public override void PostAdd()
        {
            base.PostAdd();
            L("post_add", pawn, def.defName);
        }
        public override void Tick()
        {
            base.Tick();
            L("tick", pawn);
        }
        public override void PostRemove()
        {
            base.PostRemove();
            L("post_remove", pawn, def.defName);
        }
    }

    // Lua family "quest_node". Register functions with game.classes.define("quest_node", name, { ... }).
    public class QuestNode_Lua : QuestNode
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("quest_node", luaClass, fn, a);

        public string luaClass;
        protected override void RunInt() { L("run"); }
        protected override bool TestRunInt(Slate slate) { Slate previous = LuaClasses.CurrentSlate; LuaClasses.CurrentSlate = slate; try { return LuaClasses.Bool(L("test"), true); } finally { LuaClasses.CurrentSlate = previous; } }

    }

    // Lua family "world_gen_step". Register functions with game.classes.define("world_gen_step", name, { ... }).
    public class WorldGenStep_Lua : WorldGenStep
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("world_gen_step", LuaClasses.OfDef(def), fn, a);

        public override int SeedPart => 7391042;
        public override void GenerateFresh(string seed, PlanetLayer layer) { L("generate", seed); }

    }

    // Lua family "scen_part". Register functions with game.classes.define("scen_part", name, { ... }).
    public class ScenPart_Lua : ScenPart
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("scen_part", LuaClasses.OfDef(def), fn, a);

        public override IEnumerable<string> GetSummaryListEntries(string tag) { string s = LuaClasses.Str(L("summary", tag), null); if (!string.IsNullOrEmpty(s)) yield return s; }

        public override void PostGameStart()
        {
            base.PostGameStart();
            L("post_game_start");
        }
        public override void PostWorldGenerate()
        {
            base.PostWorldGenerate();
            L("post_world_generate");
        }
        public override void GenerateIntoMap(Map map)
        {
            base.GenerateIntoMap(map);
            L("generate_into_map", map);
        }
        public override void PostMapGenerate(Map map)
        {
            base.PostMapGenerate(map);
            L("post_map_generate", map);
        }
        public override void Tick()
        {
            base.Tick();
            L("tick");
        }
    }

    // Lua family "ritual_outcome". Register functions with game.classes.define("ritual_outcome", name, { ... }).
    public class RitualOutcomeEffectWorker_Lua : RitualOutcomeEffectWorker
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("ritual_outcome", LuaClasses.OfDef(def), fn, a);

        public RitualOutcomeEffectWorker_Lua() : base()
        {
        }

        public RitualOutcomeEffectWorker_Lua(RitualOutcomeEffectDef def) : base(def)
        {
        }

        public override void Apply(float progress, Dictionary<Pawn, int> totalPresence, LordJob_Ritual jobRitual)
        {
            L("apply", progress, LuaClasses.Handles(totalPresence.Keys.Cast<object>()));
        }
    }

    // Lua family "think_node". Register functions with game.classes.define("think_node", name, { ... }).
    public class ThinkNode_Conditional_Lua : ThinkNode_Conditional
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("think_node", luaClass, fn, a);

        public string luaClass;

        protected override bool Satisfied(Pawn p)
        {
            object r = L("satisfied", p);
            return LuaClasses.IsBool(r) ? (bool)r : false;
        }
    }

    // Lua family "building". Register functions with game.classes.define("building", name, { ... }).
    public class Building_Lua : Building
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("building", LuaClasses.OfDef(def), fn, a);

        public override string GetInspectString() { string b = base.GetInspectString(); string s = LuaClasses.Str(L("inspect_string", this), null); return string.IsNullOrEmpty(s) ? b : (string.IsNullOrEmpty(b) ? s : b + "\n" + s); }

        public override void SpawnSetup(Map map, bool respawningAfterLoad)
        {
            base.SpawnSetup(map, respawningAfterLoad);
            L("spawn", this, respawningAfterLoad);
        }
        public override void DeSpawn(DestroyMode mode)
        {
            base.DeSpawn(mode);
            L("despawn", this, mode.ToString());
        }
        public override void Destroy(DestroyMode mode)
        {
            base.Destroy(mode);
            L("destroy", this, mode.ToString());
        }
        protected override void Tick()
        {
            base.Tick();
            L("tick", this);
        }
        public override void TickRare()
        {
            base.TickRare();
            L("tick_rare", this);
        }
        public override void TickLong()
        {
            base.TickLong();
            L("tick_long", this);
        }
        public override void PostApplyDamage(DamageInfo dinfo, float totalDamageDealt)
        {
            base.PostApplyDamage(dinfo, totalDamageDealt);
            L("damaged", this, totalDamageDealt);
        }
    }

    // Lua family "door". Register functions with game.classes.define("door", name, { ... }).
    public class Building_Door_Lua : Building_Door
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("door", LuaClasses.OfDef(def), fn, a);

        public override bool PawnCanOpen(Pawn p)
        {
            object r = L("can_open", this, p);
            return LuaClasses.IsBool(r) ? (bool)r : base.PawnCanOpen(p);
        }
        public override bool BlocksPawn(Pawn p)
        {
            object r = L("blocks", this, p);
            return LuaClasses.IsBool(r) ? (bool)r : base.BlocksPawn(p);
        }
        protected override void Tick()
        {
            base.Tick();
            L("tick", this);
        }
    }

    // Lua family "storage". Register functions with game.classes.define("storage", name, { ... }).
    public class Building_Storage_Lua : Building_Storage
    {
        private object L(string fn, params object[] a) => LuaClasses.Call("storage", LuaClasses.OfDef(def), fn, a);

        public override void Notify_ReceivedThing(Thing newItem)
        {
            base.Notify_ReceivedThing(newItem);
            L("received", this, newItem);
        }
        public override void Notify_LostThing(Thing newItem)
        {
            base.Notify_LostThing(newItem);
            L("lost", this, newItem);
        }
    }
}

namespace RimKit
{
    internal static class LuaClassFamilies
    {
        public static readonly string[] All = { "comp", "hediff_comp", "incident", "condition", "storyteller", "stat_part", "stat_worker", "work_giver", "job_giver", "place_worker", "recipe_worker", "thought_worker", "mental_state_worker", "need", "ability", "damage_worker", "projectile", "verb", "gen_step", "thing_set_maker", "quest_part", "lord_toil", "gene", "quest_node", "world_gen_step", "scen_part", "ritual_outcome", "think_node", "building", "door", "storage" };
    }
}
