-- Processed by: rimkit mod sync
-- Writes Defs/ThingDefs/RimLua_FromDefsLua.xml
return {
  things = {
    {
      defName = "RimLua_JobsToken",
      label = "jobs test token",
      description = "Generated by jobs mod defs.lua for RimLuaKit Phase 3 testing.",
      texPath = "Things/Item/Resource/Steel",
      stackLimit = 50,
    },
  },
}
