-- Generated by tools/gen-unc-stubs.js from aliases.json. Do not edit.
-- Canonical RimKit names (UNC). The old names are deprecated, see rimkit.lua.
---@meta

game.anomaly = game.anomaly or {}
game.audio = game.audio or {}
game.buildings = game.buildings or {}
game.config = game.config or {}
game.control = game.control or {}
game.data = game.data or {}
game.defs = game.defs or {}
game.events = game.events or {}
game.factions = game.factions or {}
game.hooks = game.hooks or {}
game.incidents = game.incidents or {}
game.input = game.input or {}
game.jobs = game.jobs or {}
game.log = game.log or {}
game.maps = game.maps or {}
game.paths = game.paths or {}
game.pawns = game.pawns or {}
game.selection = game.selection or {}
game.things = game.things or {}
game.time = game.time or {}
game.timer = game.timer or {}
game.ui = game.ui or {}
game.util = game.util or {}
game.weather = game.weather or {}
game.work = game.work or {}
game.world = game.world or {}

---@param h integer
---@return boolean
function game.pawns.is_humanlike(h) end

function game.pawns.is_colonist(...) end

function game.pawns.is_prisoner(...) end

function game.pawns.is_slave(...) end

function game.pawns.is_downed(...) end

function game.pawns.is_dead(...) end

---@param h integer
---@return boolean
function game.pawns.faction_is_player(h) end

---@param h integer
---@return string
function game.pawns.name(h) end

function game.pawns.gender(...) end

function game.pawns.age(...) end

function game.pawns.kind(...) end

---@param h integer
---@return integer
function game.pawns.map(h) end

---@param h integer
---@return number
function game.pawns.hunger(h) end

function game.pawns.rest(...) end

function game.pawns.recreation(...) end

function game.pawns.mood(...) end

function game.pawns.set_hunger(...) end

function game.pawns.set_rest(...) end

function game.pawns.health_ratio(...) end

function game.pawns.kill(...) end

function game.pawns.drafted(...) end

function game.pawns.set_drafted(...) end

function game.pawns.equipment(...) end

function game.pawns.apparel(...) end

function game.pawns.inventory(...) end

function game.pawns.carry(...) end

function game.pawns.give_hediff(...) end

function game.pawns.remove_hediff(...) end

function game.pawns.hediffs(...) end

function game.pawns.skill(...) end

function game.pawns.set_skill(...) end

function game.pawns.give_thing(...) end

function game.pawns.strip(...) end

function game.pawns.job_def(...) end

function game.pawns.end_job(...) end

function game.pawns.make_controllable(...) end

function game.pawns.release_control(...) end

function game.pawns.is_controllable(...) end

---@param h integer
---@param defName string
---@return boolean
function game.pawns.has_hediff(h, defName) end

---@param h integer
---@param defName string
---@return number
function game.pawns.hediff_severity(h, defName) end

---@param h integer
---@param defName string
---@param severity number
function game.pawns.set_hediff_severity(h, defName, severity) end

---@param h integer
---@param quality number|nil
function game.pawns.tend(h, quality) end

---@param h integer
---@param recipeDefName string
---@return boolean
function game.pawns.queue_surgery(h, recipeDefName) end

function game.things.def(...) end

function game.things.label(...) end

function game.things.label_short(...) end

function game.things.destroy(...) end

function game.things.despawn(...) end

function game.things.pos(...) end

function game.things.set_pos(...) end

function game.things.hp(...) end

function game.things.max_hp(...) end

function game.things.set_hp(...) end

function game.things.stack(...) end

function game.things.set_stack(...) end

function game.things.faction(...) end

function game.things.set_faction(...) end

function game.things.map(...) end

function game.things.spawned(...) end

---@param h integer
---@return number
function game.maps.nutrition(h) end

function game.maps.width(...) end

function game.maps.height(...) end

function game.maps.pawns(...) end

function game.maps.colonists(...) end

function game.maps.prisoners(...) end

function game.maps.things(...) end

function game.maps.things_of_def(...) end

function game.maps.spawn(...) end

function game.factions.player(...) end

function game.factions.list(...) end

function game.factions.name(...) end

function game.factions.of_def(...) end

function game.defs.get(...) end

function game.defs.exists(...) end

function game.defs.list(...) end

function game.defs.label(...) end

---@param spec table
function game.defs.register_thing(spec) end

function game.jobs.make(...) end

function game.jobs.start_job(...) end

---@param name string
---@param spec {can_do: (fun(pawn:RimPawn):boolean)|nil, execute: fun(pawn:RimPawn):boolean}
function game.jobs.register(name, spec) end

---@param pawn RimPawn
---@param name string
---@return boolean
function game.jobs.start(pawn, name) end

---@return integer
function game.time.ticks() end

---@return integer
function game.maps.current() end

function game.world.current(...) end

---@return integer
function game.selection.first() end

function game.selection.things(...) end

function game.maps.list(...) end

function game.pawns.any_player(...) end

function game.ui.message(...) end

function game.ui.letter(...) end

---@param spec {title:string|nil, body:string|nil, buttons:table}
function game.ui.window(spec) end

---@param options table
function game.ui.float_menu(options) end

--- Right-click map menus. Humans recruit/capture; entities are commandable only.
---@param fn fun(ctx:{clicked:integer, hauler:integer}): table[]|nil
function game.ui.on_map_float_menu(fn) end

---@param spec {title:string|nil, body:string|nil, checks:string[]|nil, list:string[]|nil}
function game.ui.panel(spec) end

---@param key string
---@param spec table
function game.config.register(key, spec) end

---@param key string
---@return string
function game.config.get(key) end

---@param key string
---@return boolean
function game.config.get_bool(key) end

---@param key string
---@param value any
function game.config.set(key, value) end

---@param package_id string
---@param key string
---@return string|nil
function game.data.get(package_id, key) end

---@param package_id string
---@param key string
---@param value string
function game.data.set(package_id, key, value) end

---@param package_id string
---@param key string
function game.data.remove(package_id, key) end

---@param package_id string
---@return string[]
function game.data.keys(package_id) end

---@param def string
---@return boolean
function game.input.binding_just_pressed(def) end

---@param target "ModRoot"|"Saves"|"PlayerLog"|"RimKit"
---@param package_id string|nil
function game.util.open_folder(target, package_id) end

---@param package_id string
---@param file string
---@param content string
function game.util.write_export(package_id, file, content) end

---@param h integer
---@return boolean
function game.buildings.power_on(h) end

---@param h integer
---@param on boolean
function game.buildings.set_power(h, on) end

---@param h integer
---@param on boolean
function game.buildings.flick(h, on) end

---@param h integer
---@param workType string
---@return integer
function game.work.get_priority(h, workType) end

---@param h integer
---@param workType string
---@param priority integer
function game.work.set_priority(h, workType, priority) end

---@return string[]
function game.work.list_types() end

---@param map integer|nil
---@return string
function game.weather.current(map) end

---@param def string
---@param map integer|nil
function game.weather.set(def, map) end

---@param def string
---@param map integer|nil
---@return boolean
function game.incidents.try_fire(def, map) end

---@return string[]
function game.incidents.list() end

---@param soundDef string
function game.audio.play(soundDef) end

function game.control.claim(...) end

function game.control.clear(...) end

function game.control.get(...) end

---@param pawn RimPawn
---@param x integer
---@param z integer
---@return boolean
function game.paths.can_reach(pawn, x, z) end

---@param pawn RimPawn
---@param x integer
---@param z integer
---@param sprint boolean|nil
---@return boolean
function game.paths.walk(pawn, x, z, sprint) end

---@param pawn RimPawn
---@param radius integer|nil
---@return boolean
function game.paths.wander(pawn, radius) end

---@param pawn RimPawn
---@param x integer
---@param z integer
---@return RimCell[]
function game.paths.compute(pawn, x, z) end

---@param pawn RimPawn
function game.paths.stop(pawn) end

---@return boolean
function game.anomaly.dlc_active() end

---@param h integer
---@return boolean
function game.anomaly.is_entity(h) end

---@param h integer
---@return boolean
function game.anomaly.try_set_faction_player(h) end

---@param h integer
---@return boolean
function game.anomaly.release_to_hostile(h) end

---@param mapHandle integer|nil
---@return integer[]
function game.anomaly.list_on_map(mapHandle) end

---@param name string
---@param mapHandle integer|nil
---@return integer
function game.anomaly.get_on_map(name, mapHandle) end

---@param h integer
---@param severity number|nil
function game.anomaly.knock_out(h, severity) end

---@param hauler_h integer
---@param entity_h integer|nil
---@return integer
function game.anomaly.find_platform(hauler_h, entity_h) end

---@param hauler_h integer
---@param entity_h integer
---@param platform_h integer|nil
---@return boolean
function game.anomaly.start_capture(hauler_h, entity_h, platform_h) end

--- Same as pawn.make_controllable. Draft/move like an animal.
---@param h integer
---@return boolean
function game.anomaly.recruit(h) end

---@param typeName string
---@param methodName string
---@param fn fun(ctx:RimHookCtx):boolean|nil
---@param opts RimHookOptions|nil
---@return integer hookId
function game.hooks.prefix(typeName, methodName, fn, opts) end

---@param typeName string
---@param methodName string
---@param fn fun(ctx:RimHookCtx)
---@param opts RimHookOptions|nil
---@return integer hookId
function game.hooks.postfix(typeName, methodName, fn, opts) end

---@param typeName string
---@param methodName string
---@param fn fun(ctx:RimHookCtx)
---@param opts RimHookOptions|nil
---@return integer hookId
function game.hooks.finalizer(typeName, methodName, fn, opts) end

---@param spec RimHookPatch
---@return RimHookIds
function game.hooks.patch(spec) end

---@param spec RimHookCallReplace
---@return integer|nil hookId
function game.hooks.replace_call(spec) end

---@param hookId integer
function game.hooks.remove(hookId) end

---@return { id: integer, kind: string, type: string, method: string }[]
function game.hooks.list() end

function game.hooks.has_patch(...) end

function game.hooks.type_exists(...) end

function game.hooks.method_exists(...) end

function game.hooks.check_target(...) end

function game.hooks.check_events(...) end

---@param fn fun()
function game.events.on_load(fn) end

---@param fn fun()
function game.events.on_tick(fn) end

---@param msg string
function game.log.info(msg) end

---Canonical names ("pawn.died") receive one payload table and install their Harmony patch on first use.
---Legacy names ("pawn_died") receive a RimPawn.
---@param name string
---@param fn fun(payload:table|RimPawn)
function game.events.on(name, fn) end

---@param name string
function game.events.off(name) end

---@return RimEventInfo[]
function game.events.list() end

---@param msg string
function game.log.error(msg) end

---@param ticks integer
---@param fn fun()
function game.timer.after(ticks, fn) end
