---@meta
-- Generated by src/editor/tools/gen-luau-defs.js. Do not edit.
-- One function per event: game.events.on_pawn_damaged(function(pawn, e) ... end, filter).

---@class ThingSpawnedEvent
---@field thing RimThing
---@field map RimMap
---@field def string

--- Runs fn when thing.spawned happens. The optional filter is described in docs/api/events.md.
---@param fn fun(thing: RimThing, e: ThingSpawnedEvent)
---@param filter? table
function game.events.on_thing_spawned(fn, filter) end

---@class ThingDespawnedEvent
---@field thing RimThing
---@field mode string

--- Runs fn when thing.despawned happens. The optional filter is described in docs/api/events.md.
---@param fn fun(thing: RimThing, e: ThingDespawnedEvent)
---@param filter? table
function game.events.on_thing_despawned(fn, filter) end

---@class ThingDestroyedEvent
---@field thing RimThing
---@field mode string

--- Runs fn when thing.destroyed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(thing: RimThing, e: ThingDestroyedEvent)
---@param filter? table
function game.events.on_thing_destroyed(fn, filter) end

---@class ThingDamagedEvent
---@field thing RimThing
---@field damage RimDamageInfo
---@field dealt number

--- Runs fn when thing.damaged happens. The optional filter is described in docs/api/events.md.
---@param fn fun(thing: RimThing, e: ThingDamagedEvent)
---@param filter? table
function game.events.on_thing_damaged(fn, filter) end

---@class PawnSpawnedEvent
---@field pawn RimPawn
---@field map RimMap

--- Runs fn when pawn.spawned happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnSpawnedEvent)
---@param filter? table
function game.events.on_pawn_spawned(fn, filter) end

---@class PawnDiedEvent
---@field pawn RimPawn
---@field damage RimDamageInfo
---@field culprit RimObject

--- Runs fn when pawn.died happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnDiedEvent)
---@param filter? table
function game.events.on_pawn_died(fn, filter) end

---@class PawnDamagedEvent
---@field pawn RimPawn
---@field damage RimDamageInfo
---@field dealt number

--- Runs fn when pawn.damaged happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnDamagedEvent)
---@param filter? table
function game.events.on_pawn_damaged(fn, filter) end

---@class PawnResurrectedEvent
---@field pawn RimPawn

--- Runs fn when pawn.resurrected happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnResurrectedEvent)
---@param filter? table
function game.events.on_pawn_resurrected(fn, filter) end

---@class HediffAddedEvent
---@field pawn RimPawn
---@field hediff RimObject
---@field part any

--- Runs fn when hediff.added happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: HediffAddedEvent)
---@param filter? table
function game.events.on_hediff_added(fn, filter) end

---@class HediffRemovedEvent
---@field pawn RimPawn
---@field hediff RimObject

--- Runs fn when hediff.removed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: HediffRemovedEvent)
---@param filter? table
function game.events.on_hediff_removed(fn, filter) end

---@class JobStartedEvent
---@field pawn RimPawn
---@field job RimObject
---@field target any

--- Runs fn when job.started happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: JobStartedEvent)
---@param filter? table
function game.events.on_job_started(fn, filter) end

---@class JobEndedEvent
---@field pawn RimPawn
---@field job RimObject
---@field condition any

--- Runs fn when job.ended happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: JobEndedEvent)
---@param filter? table
function game.events.on_job_ended(fn, filter) end

---@class MentalStateStartedEvent
---@field pawn RimPawn
---@field state any
---@field started any

--- Runs fn when mental_state.started happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: MentalStateStartedEvent)
---@param filter? table
function game.events.on_mental_state_started(fn, filter) end

---@class TimeSpeedChangedEvent
---@field speed any

--- Runs fn when time.speed_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: TimeSpeedChangedEvent)
---@param filter? table
function game.events.on_time_speed_changed(fn, filter) end

---@class TimeTickedEvent
---@field ticks any

--- Runs fn when time.ticked happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: TimeTickedEvent)
---@param filter? table
function game.events.on_time_ticked(fn, filter) end

---@class GameNewEvent

--- Runs fn when game.new happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: GameNewEvent)
---@param filter? table
function game.events.on_game_new(fn, filter) end

---@class GameLoadedEvent

--- Runs fn when game.loaded happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: GameLoadedEvent)
---@param filter? table
function game.events.on_game_loaded(fn, filter) end

---@class GameReadyEvent

--- Runs fn when game.ready happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: GameReadyEvent)
---@param filter? table
function game.events.on_game_ready(fn, filter) end

---@class GameSavingEvent
---@field file any

--- Runs fn when game.saving happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: GameSavingEvent)
---@param filter? table
function game.events.on_game_saving(fn, filter) end

---@class MapReadyEvent
---@field map RimMap

--- Runs fn when map.ready happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: MapReadyEvent)
---@param filter? table
function game.events.on_map_ready(fn, filter) end

---@class MapRemovedEvent
---@field map RimMap

--- Runs fn when map.removed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: MapRemovedEvent)
---@param filter? table
function game.events.on_map_removed(fn, filter) end

---@class IncidentFiredEvent
---@field incident any
---@field success any
---@field points any
---@field map RimMap

--- Runs fn when incident.fired happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: IncidentFiredEvent)
---@param filter? table
function game.events.on_incident_fired(fn, filter) end

---@class QuestAddedEvent
---@field quest RimObject
---@field name string
---@field id any

--- Runs fn when quest.added happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: QuestAddedEvent)
---@param filter? table
function game.events.on_quest_added(fn, filter) end

---@class QuestRemovedEvent
---@field quest RimObject
---@field name string
---@field id any

--- Runs fn when quest.removed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: QuestRemovedEvent)
---@param filter? table
function game.events.on_quest_removed(fn, filter) end

---@class ResearchFinishedEvent
---@field project any
---@field researcher any

--- Runs fn when research.finished happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ResearchFinishedEvent)
---@param filter? table
function game.events.on_research_finished(fn, filter) end

---@class ResearchProgressedEvent
---@field amount number
---@field researcher any

--- Runs fn when research.progressed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ResearchProgressedEvent)
---@param filter? table
function game.events.on_research_progressed(fn, filter) end

---@class LetterReceivedEvent
---@field label string
---@field def string

--- Runs fn when letter.received happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: LetterReceivedEvent)
---@param filter? table
function game.events.on_letter_received(fn, filter) end

---@class MessageShownEvent
---@field text string
---@field def string

--- Runs fn when message.shown happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: MessageShownEvent)
---@param filter? table
function game.events.on_message_shown(fn, filter) end

---@class FactionAddedEvent
---@field faction RimFaction
---@field def string

--- Runs fn when faction.added happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: FactionAddedEvent)
---@param filter? table
function game.events.on_faction_added(fn, filter) end

---@class PawnJoinedColonyEvent
---@field pawn RimPawn
---@field from any

--- Runs fn when pawn.joined_colony happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnJoinedColonyEvent)
---@param filter? table
function game.events.on_pawn_joined_colony(fn, filter) end

---@class PawnDownedEvent
---@field pawn RimPawn

--- Runs fn when pawn.downed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnDownedEvent)
---@param filter? table
function game.events.on_pawn_downed(fn, filter) end

---@class PawnStoodUpEvent
---@field pawn RimPawn

--- Runs fn when pawn.stood_up happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnStoodUpEvent)
---@param filter? table
function game.events.on_pawn_stood_up(fn, filter) end

---@class PawnDraftedChangedEvent
---@field pawn RimPawn
---@field drafted any

--- Runs fn when pawn.drafted_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnDraftedChangedEvent)
---@param filter? table
function game.events.on_pawn_drafted_changed(fn, filter) end

---@class PawnBornEvent
---@field pawn RimPawn

--- Runs fn when pawn.born happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnBornEvent)
---@param filter? table
function game.events.on_pawn_born(fn, filter) end

---@class PawnBirthdayEvent
---@field pawn RimPawn
---@field age any

--- Runs fn when pawn.birthday happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnBirthdayEvent)
---@param filter? table
function game.events.on_pawn_birthday(fn, filter) end

---@class PawnEquippedEvent
---@field pawn RimPawn
---@field thing RimThing

--- Runs fn when pawn.equipped happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnEquippedEvent)
---@param filter? table
function game.events.on_pawn_equipped(fn, filter) end

---@class PawnWoreEvent
---@field pawn RimPawn
---@field thing RimThing

--- Runs fn when pawn.wore happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnWoreEvent)
---@param filter? table
function game.events.on_pawn_wore(fn, filter) end

---@class BillCompletedEvent
---@field pawn RimPawn
---@field recipe any

--- Runs fn when bill.completed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: BillCompletedEvent)
---@param filter? table
function game.events.on_bill_completed(fn, filter) end

---@class PlantHarvestedEvent
---@field plant any
---@field pawn RimPawn

--- Runs fn when plant.harvested happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PlantHarvestedEvent)
---@param filter? table
function game.events.on_plant_harvested(fn, filter) end

---@class ConstructionFinishedEvent
---@field frame any
---@field def string
---@field pawn RimPawn

--- Runs fn when construction.finished happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ConstructionFinishedEvent)
---@param filter? table
function game.events.on_construction_finished(fn, filter) end

---@class RecipeAppliedEvent
---@field pawn RimPawn
---@field recipe any
---@field doer any

--- Runs fn when recipe.applied happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: RecipeAppliedEvent)
---@param filter? table
function game.events.on_recipe_applied(fn, filter) end

---@class HediffTendedEvent
---@field pawn RimPawn
---@field hediff RimObject
---@field quality any

--- Runs fn when hediff.tended happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: HediffTendedEvent)
---@param filter? table
function game.events.on_hediff_tended(fn, filter) end

---@class MentalStateEndedEvent
---@field pawn RimPawn
---@field state any

--- Runs fn when mental_state.ended happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: MentalStateEndedEvent)
---@param filter? table
function game.events.on_mental_state_ended(fn, filter) end

---@class InspirationGainedEvent
---@field pawn RimPawn
---@field started any

--- Runs fn when inspiration.gained happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: InspirationGainedEvent)
---@param filter? table
function game.events.on_inspiration_gained(fn, filter) end

---@class ThoughtGainedEvent
---@field pawn RimPawn
---@field thought any

--- Runs fn when thought.gained happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ThoughtGainedEvent)
---@param filter? table
function game.events.on_thought_gained(fn, filter) end

---@class RelationFormedEvent
---@field pawn RimPawn
---@field relation any
---@field other RimPawn

--- Runs fn when relation.formed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: RelationFormedEvent)
---@param filter? table
function game.events.on_relation_formed(fn, filter) end

---@class RelationEndedEvent
---@field pawn RimPawn
---@field relation any
---@field other RimPawn

--- Runs fn when relation.ended happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: RelationEndedEvent)
---@param filter? table
function game.events.on_relation_ended(fn, filter) end

---@class InteractionDoneEvent
---@field pawn RimPawn
---@field recipient any
---@field interaction any
---@field success any

--- Runs fn when interaction.done happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: InteractionDoneEvent)
---@param filter? table
function game.events.on_interaction_done(fn, filter) end

---@class SkillLearnedEvent
---@field pawn RimPawn
---@field skill any
---@field xp any
---@field level any

--- Runs fn when skill.learned happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: SkillLearnedEvent)
---@param filter? table
function game.events.on_skill_learned(fn, filter) end

---@class ProjectileHitEvent
---@field projectile any
---@field target any
---@field launcher any

--- Runs fn when projectile.hit happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ProjectileHitEvent)
---@param filter? table
function game.events.on_projectile_hit(fn, filter) end

---@class ExplosionOccurredEvent
---@field map RimMap
---@field x any
---@field z any
---@field radius any
---@field damage_def any

--- Runs fn when explosion.occurred happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ExplosionOccurredEvent)
---@param filter? table
function game.events.on_explosion_occurred(fn, filter) end

---@class MeleeHitEvent
---@field attacker any
---@field target any

--- Runs fn when melee.hit happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: MeleeHitEvent)
---@param filter? table
function game.events.on_melee_hit(fn, filter) end

---@class MapGeneratedEvent
---@field map RimMap

--- Runs fn when map.generated happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: MapGeneratedEvent)
---@param filter? table
function game.events.on_map_generated(fn, filter) end

---@class WorldObjectAddedEvent
---@field object any
---@field def string
---@field tile any

--- Runs fn when world_object.added happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: WorldObjectAddedEvent)
---@param filter? table
function game.events.on_world_object_added(fn, filter) end

---@class WorldObjectRemovedEvent
---@field object any
---@field def string
---@field tile any

--- Runs fn when world_object.removed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: WorldObjectRemovedEvent)
---@param filter? table
function game.events.on_world_object_removed(fn, filter) end

---@class CaravanFormedEvent
---@field caravan any

--- Runs fn when caravan.formed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: CaravanFormedEvent)
---@param filter? table
function game.events.on_caravan_formed(fn, filter) end

---@class WeatherChangedEvent
---@field map RimMap
---@field weather any

--- Runs fn when weather.changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: WeatherChangedEvent)
---@param filter? table
function game.events.on_weather_changed(fn, filter) end

---@class ConditionStartedEvent
---@field condition any
---@field label string

--- Runs fn when condition.started happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ConditionStartedEvent)
---@param filter? table
function game.events.on_condition_started(fn, filter) end

---@class ConditionEndedEvent
---@field condition any
---@field label string

--- Runs fn when condition.ended happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ConditionEndedEvent)
---@param filter? table
function game.events.on_condition_ended(fn, filter) end

---@class TimeHourChangedEvent
---@field ticks any

--- Runs fn when time.hour_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: TimeHourChangedEvent)
---@param filter? table
function game.events.on_time_hour_changed(fn, filter) end

---@class TimeDayChangedEvent
---@field ticks any

--- Runs fn when time.day_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: TimeDayChangedEvent)
---@param filter? table
function game.events.on_time_day_changed(fn, filter) end

---@class TimeQuadrumChangedEvent
---@field ticks any

--- Runs fn when time.quadrum_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: TimeQuadrumChangedEvent)
---@param filter? table
function game.events.on_time_quadrum_changed(fn, filter) end

---@class TimeYearChangedEvent
---@field ticks any

--- Runs fn when time.year_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: TimeYearChangedEvent)
---@param filter? table
function game.events.on_time_year_changed(fn, filter) end

---@class TradeCompletedEvent
---@field traded any

--- Runs fn when trade.completed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: TradeCompletedEvent)
---@param filter? table
function game.events.on_trade_completed(fn, filter) end

---@class QuestAcceptedEvent
---@field quest RimObject
---@field name string
---@field id any

--- Runs fn when quest.accepted happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: QuestAcceptedEvent)
---@param filter? table
function game.events.on_quest_accepted(fn, filter) end

---@class QuestEndedEvent
---@field quest RimObject
---@field name string
---@field id any
---@field outcome any

--- Runs fn when quest.ended happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: QuestEndedEvent)
---@param filter? table
function game.events.on_quest_ended(fn, filter) end

---@class ResearchStartedEvent
---@field project any

--- Runs fn when research.started happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ResearchStartedEvent)
---@param filter? table
function game.events.on_research_started(fn, filter) end

---@class PowerChangedEvent
---@field thing RimThing
---@field on any

--- Runs fn when power.changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(thing: RimThing, e: PowerChangedEvent)
---@param filter? table
function game.events.on_power_changed(fn, filter) end

---@class DesignationAddedEvent
---@field def string
---@field thing RimThing
---@field x any
---@field z any

--- Runs fn when designation.added happens. The optional filter is described in docs/api/events.md.
---@param fn fun(thing: RimThing, e: DesignationAddedEvent)
---@param filter? table
function game.events.on_designation_added(fn, filter) end

---@class DesignationRemovedEvent
---@field def string
---@field thing RimThing
---@field x any
---@field z any

--- Runs fn when designation.removed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(thing: RimThing, e: DesignationRemovedEvent)
---@param filter? table
function game.events.on_designation_removed(fn, filter) end

---@class ZoneCreatedEvent
---@field id any
---@field label string
---@field type any

--- Runs fn when zone.created happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ZoneCreatedEvent)
---@param filter? table
function game.events.on_zone_created(fn, filter) end

---@class ZoneRemovedEvent
---@field id any
---@field label string
---@field type any

--- Runs fn when zone.removed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ZoneRemovedEvent)
---@param filter? table
function game.events.on_zone_removed(fn, filter) end

---@class FactionGoodwillChangedEvent
---@field faction RimFaction
---@field other RimPawn
---@field goodwill any

--- Runs fn when faction.goodwill_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: FactionGoodwillChangedEvent)
---@param filter? table
function game.events.on_faction_goodwill_changed(fn, filter) end

---@class PawnIdeoChangedEvent
---@field pawn RimPawn
---@field ideo any

--- Runs fn when pawn.ideo_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnIdeoChangedEvent)
---@param filter? table
function game.events.on_pawn_ideo_changed(fn, filter) end

---@class IdeoPreceptAddedEvent
---@field ideo any
---@field precept any

--- Runs fn when ideo.precept_added happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: IdeoPreceptAddedEvent)
---@param filter? table
function game.events.on_ideo_precept_added(fn, filter) end

---@class RoyaltyTitleChangedEvent
---@field pawn RimPawn
---@field faction RimFaction
---@field title any

--- Runs fn when royalty.title_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: RoyaltyTitleChangedEvent)
---@param filter? table
function game.events.on_royalty_title_changed(fn, filter) end

---@class AnomalyLevelChangedEvent
---@field level any

--- Runs fn when anomaly.level_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: AnomalyLevelChangedEvent)
---@param filter? table
function game.events.on_anomaly_level_changed(fn, filter) end

---@class AbilityUsedEvent
---@field pawn RimPawn
---@field ability RimObject
---@field target any

--- Runs fn when ability.used happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: AbilityUsedEvent)
---@param filter? table
function game.events.on_ability_used(fn, filter) end

---@class ShotFiredEvent
---@field shooter any
---@field target any
---@field verb any

--- Runs fn when shot.fired happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ShotFiredEvent)
---@param filter? table
function game.events.on_shot_fired(fn, filter) end

---@class PawnLeftMapEvent
---@field pawn RimPawn
---@field map RimMap

--- Runs fn when pawn.left_map happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnLeftMapEvent)
---@param filter? table
function game.events.on_pawn_left_map(fn, filter) end

---@class LetterOpenedEvent
---@field label string

--- Runs fn when letter.opened happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: LetterOpenedEvent)
---@param filter? table
function game.events.on_letter_opened(fn, filter) end

---@class LetterChoiceEvent
---@field tag any
---@field index any
---@field label string

--- Runs fn when letter.choice happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: LetterChoiceEvent)
---@param filter? table
function game.events.on_letter_choice(fn, filter) end

---@class ModDisabledEvent
---@field mod any
---@field where any

--- Runs fn when mod.disabled happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ModDisabledEvent)
---@param filter? table
function game.events.on_mod_disabled(fn, filter) end

---@class ModOverBudgetEvent
---@field mod any
---@field avg_us any

--- Runs fn when mod.over_budget happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ModOverBudgetEvent)
---@param filter? table
function game.events.on_mod_over_budget(fn, filter) end

---@class OptionsChangedEvent
---@field package_id any
---@field key any
---@field value any

--- Runs fn when options.changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: OptionsChangedEvent)
---@param filter? table
function game.events.on_options_changed(fn, filter) end

---@class SelectionChangedEvent
---@field count number

--- Runs fn when selection.changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: SelectionChangedEvent)
---@param filter? table
function game.events.on_selection_changed(fn, filter) end

---@class SelectionClearedEvent

--- Runs fn when selection.cleared happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: SelectionClearedEvent)
---@param filter? table
function game.events.on_selection_cleared(fn, filter) end

---@class WindowOpenedEvent
---@field class any

--- Runs fn when window.opened happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: WindowOpenedEvent)
---@param filter? table
function game.events.on_window_opened(fn, filter) end

---@class PawnLeftColonyEvent
---@field pawn RimPawn
---@field to any

--- Runs fn when pawn.left_colony happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnLeftColonyEvent)
---@param filter? table
function game.events.on_pawn_left_colony(fn, filter) end

---@class PawnEscapedEvent
---@field pawn RimPawn
---@field initiator any

--- Runs fn when pawn.escaped happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: PawnEscapedEvent)
---@param filter? table
function game.events.on_pawn_escaped(fn, filter) end

---@class WorkCompletedEvent
---@field pawn RimPawn
---@field job RimObject
---@field work_type any

--- Runs fn when work.completed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: WorkCompletedEvent)
---@param filter? table
function game.events.on_work_completed(fn, filter) end

---@class ItemCraftedEvent
---@field thing RimThing
---@field recipe any
---@field pawn RimPawn

--- Runs fn when item.crafted happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ItemCraftedEvent)
---@param filter? table
function game.events.on_item_crafted(fn, filter) end

---@class MiningCompletedEvent
---@field def string
---@field x any
---@field z any
---@field pawn RimPawn

--- Runs fn when mining.completed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: MiningCompletedEvent)
---@param filter? table
function game.events.on_mining_completed(fn, filter) end

---@class ConstructionStartedEvent
---@field frame any
---@field def string
---@field pawn RimPawn

--- Runs fn when construction.started happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ConstructionStartedEvent)
---@param filter? table
function game.events.on_construction_started(fn, filter) end

---@class BuildingDeconstructedEvent
---@field pawn RimPawn
---@field thing RimThing
---@field def string
---@field x any
---@field z any

--- Runs fn when building.deconstructed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: BuildingDeconstructedEvent)
---@param filter? table
function game.events.on_building_deconstructed(fn, filter) end

---@class ThingRepairedEvent
---@field pawn RimPawn
---@field thing RimThing
---@field def string

--- Runs fn when thing.repaired happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ThingRepairedEvent)
---@param filter? table
function game.events.on_thing_repaired(fn, filter) end

---@class ThingHauledEvent
---@field pawn RimPawn
---@field thing RimThing
---@field def string

--- Runs fn when thing.hauled happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ThingHauledEvent)
---@param filter? table
function game.events.on_thing_hauled(fn, filter) end

---@class ThingDroppedEvent
---@field pawn RimPawn
---@field thing RimThing
---@field def string
---@field x any
---@field z any

--- Runs fn when thing.dropped happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ThingDroppedEvent)
---@param filter? table
function game.events.on_thing_dropped(fn, filter) end

---@class HediffHealedEvent
---@field pawn RimPawn
---@field hediff RimObject

--- Runs fn when hediff.healed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: HediffHealedEvent)
---@param filter? table
function game.events.on_hediff_healed(fn, filter) end

---@class ImmunityGainedEvent
---@field pawn RimPawn
---@field disease any

--- Runs fn when immunity.gained happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ImmunityGainedEvent)
---@param filter? table
function game.events.on_immunity_gained(fn, filter) end

---@class ThoughtLostEvent
---@field pawn RimPawn
---@field thought any

--- Runs fn when thought.lost happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: ThoughtLostEvent)
---@param filter? table
function game.events.on_thought_lost(fn, filter) end

---@class SocialFightStartedEvent
---@field pawn RimPawn
---@field other RimPawn

--- Runs fn when social_fight.started happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: SocialFightStartedEvent)
---@param filter? table
function game.events.on_social_fight_started(fn, filter) end

---@class SkillLearningSaturatedEvent
---@field pawn RimPawn
---@field skill any

--- Runs fn when skill.learning_saturated happens. The optional filter is described in docs/api/events.md.
---@param fn fun(pawn: RimPawn, e: SkillLearningSaturatedEvent)
---@param filter? table
function game.events.on_skill_learning_saturated(fn, filter) end

---@class FireStartedEvent
---@field fire any
---@field map RimMap
---@field x any
---@field z any

--- Runs fn when fire.started happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: FireStartedEvent)
---@param filter? table
function game.events.on_fire_started(fn, filter) end

---@class FireEndedEvent
---@field fire any
---@field map RimMap
---@field x any
---@field z any

--- Runs fn when fire.ended happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: FireEndedEvent)
---@param filter? table
function game.events.on_fire_ended(fn, filter) end

---@class WorldGeneratedEvent
---@field seed any

--- Runs fn when world.generated happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: WorldGeneratedEvent)
---@param filter? table
function game.events.on_world_generated(fn, filter) end

---@class CaravanArrivedEvent
---@field caravan any
---@field tile any

--- Runs fn when caravan.arrived happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: CaravanArrivedEvent)
---@param filter? table
function game.events.on_caravan_arrived(fn, filter) end

---@class SiteVisitedEvent
---@field caravan any
---@field site any
---@field def string

--- Runs fn when site.visited happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: SiteVisitedEvent)
---@param filter? table
function game.events.on_site_visited(fn, filter) end

---@class GoodsDeliveredEvent
---@field thing RimThing
---@field map RimMap
---@field x any
---@field z any

--- Runs fn when goods.delivered happens. The optional filter is described in docs/api/events.md.
---@param fn fun(thing: RimThing, e: GoodsDeliveredEvent)
---@param filter? table
function game.events.on_goods_delivered(fn, filter) end

---@class SilverChangedEvent
---@field silver any
---@field delta any

--- Runs fn when silver.changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: SilverChangedEvent)
---@param filter? table
function game.events.on_silver_changed(fn, filter) end

---@class ResearchMilestoneEvent
---@field project any
---@field percent any

--- Runs fn when research.milestone happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: ResearchMilestoneEvent)
---@param filter? table
function game.events.on_research_milestone(fn, filter) end

---@class RoomChangedEvent
---@field map RimMap

--- Runs fn when room.changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: RoomChangedEvent)
---@param filter? table
function game.events.on_room_changed(fn, filter) end

---@class FactionRelationChangedEvent
---@field faction RimFaction
---@field other RimPawn
---@field previous any
---@field kind string

--- Runs fn when faction.relation_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: FactionRelationChangedEvent)
---@param filter? table
function game.events.on_faction_relation_changed(fn, filter) end

---@class FactionLeaderChangedEvent
---@field faction RimFaction
---@field leader any

--- Runs fn when faction.leader_changed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: FactionLeaderChangedEvent)
---@param filter? table
function game.events.on_faction_leader_changed(fn, filter) end

---@class GizmoClickedEvent
---@field label string
---@field class any

--- Runs fn when gizmo.clicked happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: GizmoClickedEvent)
---@param filter? table
function game.events.on_gizmo_clicked(fn, filter) end

---@class KeyPressedEvent
---@field key any
---@field shift any
---@field control any
---@field alt any

--- Runs fn when key.pressed happens. The optional filter is described in docs/api/events.md.
---@param fn fun(e: KeyPressedEvent)
---@param filter? table
function game.events.on_key_pressed(fn, filter) end
