---@meta
-- Generated by infrastructure/tools/gen-tweaks.js from src/api/tweaks.json. Do not edit by hand.

---@alias RimTweakName "pawn.hunger_rate"|"pawn.rest_fall_rate"|"pawn.joy_fall_rate"|"pawn.carry_capacity"|"plant.growth_rate"|"thing.max_hit_points"|"thing.market_value"|"time.rate_multiplier"|"shot.hit_factor_shooter"|"health.bleed_rate"|"health.pain_total"|"social.opinion"|"power.plant_output"

---@class RimTweakArgs
---@field value number The value the game computed
---@field instance any The object the value belongs to (a pawn, thing or tracker), nil for static methods
---@field args any[] The arguments of the call

---@class RimTweakInfo
---@field name string
---@field type string
---@field method string
---@field result string
---@field doc string

game.tweaks = game.tweaks or {}

--- Every tweak point.
---@return RimTweakInfo[]
function game.tweaks.list() end

--- Changes a value at a named tweak point. fn returns the new value, or nil to keep the game's. Returns a hook id.
---@param name RimTweakName
---@param fn fun(args: RimTweakArgs): number?
---@param opts? table
---@return integer
function game.tweaks.on(name, fn, opts) end

--- Removes a tweak by its hook id.
---@param id integer
function game.tweaks.off(id) end
