#!/usr/bin/env node
// Generates the docs page and the editor stubs for the tweak catalog (src/api/tweaks.json).
//   infrastructure/docs/api/tweaks.md        one row per tweak point
//   src/editor/stubs/rimkit_tweaks.lua       game.tweaks with the tweak names as an alias, so the editor completes them
// Run: node infrastructure/tools/gen-tweaks.js [--check]
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "../..");
const catalog = JSON.parse(fs.readFileSync(path.join(root, "src/api/tweaks.json"), "utf8")).tweaks;
let problems = 0;
const seen = new Set();
for (const t of catalog) {
  if (!/^[a-z_]+\.[a-z_]+$/.test(t.name)) { console.log(`tweaks: bad name ${t.name}`); problems++; }
  if (seen.has(t.name)) { console.log(`tweaks: duplicate ${t.name}`); problems++; }
  seen.add(t.name);
  for (const k of ["type", "method", "kind", "result", "doc"]) if (!t[k]) { console.log(`tweaks: ${t.name} has no ${k}`); problems++; }
}

const lua = [
  "---@meta",
  "-- Generated by infrastructure/tools/gen-tweaks.js from src/api/tweaks.json. Do not edit by hand.",
  "",
  `---@alias RimTweakName ${catalog.map((t) => JSON.stringify(t.name)).join("|")}`,
  "",
  "---@class RimTweakArgs",
  "---@field value number The value the game computed",
  "---@field instance any The object the value belongs to (a pawn, thing or tracker), nil for static methods",
  "---@field args any[] The arguments of the call",
  "",
  "---@class RimTweakInfo",
  "---@field name string",
  "---@field type string",
  "---@field method string",
  "---@field result string",
  "---@field doc string",
  "",
  "game.tweaks = game.tweaks or {}",
  "",
  "--- Every tweak point.",
  "---@return RimTweakInfo[]",
  "function game.tweaks.list() end",
  "",
  "--- Changes a value at a named tweak point. fn returns the new value, or nil to keep the game's. Returns a hook id.",
  "---@param name RimTweakName",
  "---@param fn fun(args: RimTweakArgs): number?",
  "---@param opts? table",
  "---@return integer",
  "function game.tweaks.on(name, fn, opts) end",
  "",
  "--- Removes a tweak by its hook id.",
  "---@param id integer",
  "function game.tweaks.off(id) end",
  "",
].join("\n");

const md =
  "<!-- Generated by infrastructure/tools/gen-tweaks.js from src/api/tweaks.json. Do not edit by hand. -->\n" +
  `# Tweak catalog

A tweak point is a named place where a mod can change a value, without knowing which game method computes it. \`game.tweaks.on(name, fn)\` installs the hook for you and passes \`{ value, instance, args }\` to your function, which returns the new value (or nil to keep the game's). The kit is Experimental in the [stability tiers](stability.md).

\`\`\`lua
-- Colonists get hungry half as fast
game.tweaks.on("pawn.hunger_rate", function(t) return t.value * 0.5 end)

-- Better shooters hit more often (the Super Accuracy mod, in one line)
game.tweaks.on("shot.hit_factor_shooter", function(t) return math.min(1, t.value + 0.2) end)
\`\`\`

A tweak is a hook underneath, so the same rules apply: it runs on whichever thread runs the method, and a tweak on a method the game calls thousands of times a tick costs time. \`game.hooks.list()\` shows what each one costs. For stats, \`game.stats.modify\` is usually the better tool, see [research and stats](research.md). To change a def's number once instead of every call, use [\`game.defs.set\`](defs.md).

The catalog is data: \`src/api/tweaks.json\`. Adding a tweak point is one row, and this page and the editor completions are generated from it. The game-update watch checks every row's target against the running game.

## Tweak points

| Name | Result | Target | What it changes |
|------|--------|--------|-----------------|
${catalog.map((t) => `| \`${t.name}\` | ${t.result} | \`${t.type}.${t.method}\` | ${t.doc} |`).join("\n")}
`;

const luaPath = path.join(root, "src/editor/stubs/rimkit_tweaks.lua");
const mdPath = path.join(root, "infrastructure/docs/api/tweaks.md");
const norm = (s) => s.replace(/\r/g, "");
if (process.argv.includes("--check")) {
  const ok = fs.existsSync(luaPath) && norm(fs.readFileSync(luaPath, "utf8")) === lua && fs.existsSync(mdPath) && norm(fs.readFileSync(mdPath, "utf8")) === md;
  if (!ok) { console.log("tweaks: generated files are out of date. Run node infrastructure/tools/gen-tweaks.js"); problems++; }
} else if (!problems) {
  fs.writeFileSync(luaPath, lua);
  fs.writeFileSync(mdPath, md);
  fs.writeFileSync(path.join(root, "src/editor/tweaks.json"), fs.readFileSync(path.join(root, "src/api/tweaks.json")));
}
console.log(`tweaks: ${catalog.length} tweak points, ${problems} problem(s)`);
process.exit(problems ? 1 : 0);
