#!/usr/bin/env node
// Writes CHANGES.md in the repository root from infrastructure/docs/changes.md, so the change log is readable on GitHub and on the
// docs site from one source. Relative links are rewritten to work from the root.
// Run: node infrastructure/tools/gen-changes.js [--check]
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "../..");
const source = path.join(root, "infrastructure/docs/changes.md");
const target = path.join(root, "CHANGES.md");

let text = fs.readFileSync(source, "utf8").replace(/\r/g, "");
text = text.replace(/\]\((?!https?:|#|mailto:)([^)\s]+)\)/g, (m, link) => "](infrastructure/docs/" + link + ")");
text = text.replace("This page is the source of the `CHANGES.md` file in the repository root.", "This file is generated from `infrastructure/docs/changes.md`. Edit that one.");
const out = "<!-- Generated by infrastructure/tools/gen-changes.js from infrastructure/docs/changes.md. Do not edit by hand. -->\n" + text;

if (process.argv.includes("--check")) {
  const now = fs.existsSync(target) ? fs.readFileSync(target, "utf8").replace(/\r/g, "") : "";
  if (now !== out) {
    console.log("changes: CHANGES.md is out of date. Run node infrastructure/tools/gen-changes.js");
    process.exit(1);
  }
  console.log("changes: CHANGES.md up to date");
} else {
  fs.writeFileSync(target, out);
  console.log("changes: wrote CHANGES.md");
}
