#!/usr/bin/env node
// Generates infrastructure/docs/guide/cli.md from the usage text in src/native/cli/main.cpp, so the command list can never drift from the
// program. The prose around it is in this file. Run: node infrastructure/tools/gen-cli-doc.js [--check]
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "../..");
const out = path.join(root, "infrastructure/docs/guide/cli.md");
const src = fs.readFileSync(path.join(root, "src/native/cli/main.cpp"), "utf8");
const usage = /static void usage\(\) \{([\s\S]*?)\n\}/.exec(src);
if (!usage) throw new Error("usage() not found in main.cpp");
const rows = [];
for (const m of usage[1].matchAll(/<<\s*"  (rimkit [^"]*?)\\n"/g)) {
  const line = m[1];
  const parts = /^(rimkit .*?\S) {2,}(\S.*)$/.exec(line) || /^(rimkit .*\]) ([A-Z].*)$/.exec(line);
  rows.push(parts ? [parts[1].trim(), parts[2].trim()] : [line.trim(), line.trim() === "rimkit help" ? "Print this list" : ""]);
}

const text = [];
text.push("<!-- Generated by infrastructure/tools/gen-cli-doc.js from src/native/cli/main.cpp. Do not edit by hand. -->");
text.push("# CLI reference");
text.push("");
text.push("`rimkit` is one program that creates, checks, tests, ships and publishes mods. It needs no game running, except `diag`, which reads the game's log. Run it from your mod's folder or give a path.");
text.push("");
text.push("## Commands");
text.push("");
text.push("| Command | What it does |");
text.push("|---------|--------------|");
for (const [cmd, what] of rows) text.push(`| \`${cmd.replace(/\|/g, "\\|")}\` | ${what.replace(/\|/g, "\\|")} |`);
text.push("");
text.push("## What `sync` writes");
text.push("");
text.push("`rimkit mod sync` (also run first by `ship`) makes the files the game needs from the files you edit:");
text.push("");
text.push("| You edit | It writes |");
text.push("|----------|-----------|");
text.push("| `meta.lua` | `About/About.xml`, `About/RimKit.json` (capabilities, API level, budget) and `LoadFolders.xml` for `version_folders` |");
text.push("| `Defs/*.lua` | `Defs/*.xml` next to each file, see [Defs in Lua](defs-xml.md#defs-in-lua) |");
text.push("| `Languages/*/Keyed/*.lua` | `Languages/*/Keyed/*.xml`, see [Strings in Lua](defs-xml.md#strings-in-lua) |");
text.push("");
text.push("## Maintaining RimKit itself");
text.push("");
text.push("`rimkit update` is for people who work on this repository. It needs Node.js and runs the tools in `infrastructure/tools`:");
text.push("");
text.push("| Command | What it does |");
text.push("|---------|--------------|");
text.push("| `rimkit update` | Fixes the version in every file from `src/api/VERSION`, rebuilds the kit table, regenerates the docs, stubs and change log, and runs the lints |");
text.push("| `rimkit update --check` | The same, but only checks. Exits 1 when something is out of date and writes nothing. Use it in CI |");
text.push("| `rimkit update --release` | Also writes `mod/Auth/allowlist.json` from the built files and verifies it (`release.js`). Run `rimkit build` first, the hashes must be of the built files |");
text.push("| `rimkit update --release --deploy <folder>` | Also copies `mod/` to the folder and verifies the copy. It never guesses a folder: nothing is copied into the game unless you name it |");
text.push("");
text.push("## Environment");
text.push("");
text.push("| Variable | Used for |");
text.push("|----------|----------|");
text.push("| `RIMKIT_AUTHOR` | The author and package id prefix `mod create` writes |");
text.push("| `RIMKIT_CORE` | Path to `rimlua_core.dll` for `mod test`, when it is not next to `rimkit.exe` |");
text.push("| `RIMWORLD_MODS` | The game's `Mods` folder for `mod ship`, when it is not found by itself |");
text.push("");
text.push("## Exit codes");
text.push("");
text.push("`0` means success. `1` means a problem was found (a failing test, a content error, a Lua error in a Defs script, a refused overwrite). `2` means the command was used wrongly. This makes every command usable in CI, see the [publishing guide](publishing.md).");
text.push("");
const body = text.join("\n");

if (process.argv.includes("--check")) {
  const same = fs.existsSync(out) && fs.readFileSync(out, "utf8").replace(/\r/g, "") === body;
  console.log(`cli doc: ${rows.length} commands, ${same ? "up to date" : "OUT OF DATE, run node infrastructure/tools/gen-cli-doc.js"}`);
  process.exit(same ? 0 : 1);
}
fs.writeFileSync(out, body);
console.log(`cli doc: wrote ${rows.length} commands`);
