#!/usr/bin/env node
// Generates infrastructure/docs/api/ops.md: every host operation the game side answers, with its tier, the version that added it and the
// Lua function that wraps it. Ops are what a Lua call becomes (`game.pawns.skills(p)` calls `pawn.skills`), so this is the full surface
// under the Lua API, useful for mocks (`t.mock("pawn.skills", ...)`), `rim.invoke` and reading the host source.
// Sources: src/host/**/*.cs and src/api/kits.json. Run: node infrastructure/tools/gen-ops-doc.js [--check]
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "../..");
const out = path.join(root, "infrastructure/docs/api/ops.md");
const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? (["obj", "bin"].includes(e.name) ? [] : walk(path.join(dir, e.name))) : [path.join(dir, e.name)]));

const registerRe = /(?:ApiRegistry\.Register|\bR)\(\s*"([^"]+)"\s*,\s*[^,]+?(?:,\s*"([^"]*)")?(?:,\s*"([^"]*)")?\s*\)\s*;/g;
const dlcRe = /\bD\(\s*(?:"(\w+)"|(\w+))\s*,\s*"([^"]+)"/g;
const ops = new Map();
for (const file of walk(path.join(root, "src/host")).filter((f) => f.endsWith(".cs"))) {
  const text = fs.readFileSync(file, "utf8");
  const where = path.basename(file);
  for (const m of text.matchAll(registerRe)) ops.set(m[1], { tier: m[2] || "gameplay", since: m[3] || "", file: where, dlc: "" });
  for (const m of text.matchAll(dlcRe)) ops.set(m[3], { tier: "advanced", since: "", file: where, dlc: m[1] || "" });
}
const gameApi = path.join(root, "src/host/GameApi.cs");
for (const m of fs.readFileSync(gameApi, "utf8").matchAll(/case "([a-z][a-z0-9_]*\.[a-z0-9_.]+)"/g)) {
  if (!ops.has(m[1])) ops.set(m[1], { tier: "legacy", since: "", file: "GameApi.cs", dlc: "" });
}

const kits = JSON.parse(fs.readFileSync(path.join(root, "src/api/kits.json"), "utf8")).kits;
const wraps = new Map();
for (const k of kits) for (const f of k.fns) wraps.set(`${k.op}.${f.name}`, `game.${k.domain}.${f.name}`);

const byDomain = new Map();
for (const [op, info] of [...ops].sort((a, b) => a[0].localeCompare(b[0]))) {
  const d = op.split(".")[0];
  if (!byDomain.has(d)) byDomain.set(d, []);
  byDomain.get(d).push([op, info]);
}

const text = [];
text.push("<!-- Generated by infrastructure/tools/gen-ops-doc.js from src/host and src/api/kits.json. Do not edit by hand. -->");
text.push("# Host operations");
text.push("");
text.push(`The game side answers ${ops.size} named operations in ${byDomain.size} domains. Every Lua function is a thin wrapper over one of them: \`game.pawns.skills(p)\` sends \`pawn.skills\` with \`{ h = <pawn> }\`. You rarely need the op name, but it is what \`t.mock("pawn.skills", ...)\` in a [test](../guide/testing.md) replaces, what the audit log and the [profiler](../guide/performance.md) print, and what \`rim.invoke\` takes. A mock for a name that is not in this list is refused with \`RK1001\`.`);
text.push("");
text.push("| Tier | Meaning |");
text.push("|------|---------|");
text.push("| gameplay | Reads and changes the colony. Allowed for every mod |");
text.push("| util | Helpers such as JSON, files in the mod folder, key bindings |");
text.push("| advanced | Reflection, hooks, def changes. Gated by capabilities and settings |");
text.push("| legacy | The older operations from before the kit tables. They still work and have the same names |");
text.push("");
text.push("Subject-first calls name the subject `h`. A DLC operation fails with `RK3003` when that expansion is not active.");
for (const [d, list] of byDomain) {
  text.push("");
  text.push(`## ${d}`);
  text.push("");
  text.push("| Operation | Tier | Since | Lua function |");
  text.push("|-----------|------|-------|--------------|");
  for (const [op, info] of list) {
    const lua = wraps.get(op);
    text.push(`| \`${op}\` | ${info.tier}${info.dlc ? " (" + info.dlc + ")" : ""} | ${info.since || ""} | ${lua ? "`" + lua + "`" : "native binding"} |`);
  }
}
text.push("");
const body = text.join("\n");

if (process.argv.includes("--check")) {
  const same = fs.existsSync(out) && fs.readFileSync(out, "utf8").replace(/\r/g, "") === body;
  console.log(`ops doc: ${ops.size} ops, ${same ? "up to date" : "OUT OF DATE, run node infrastructure/tools/gen-ops-doc.js"}`);
  process.exit(same ? 0 : 1);
}
fs.writeFileSync(out, body);
console.log(`ops doc: wrote ${ops.size} ops in ${byDomain.size} domains`);
