-- Run with: rimkit mod test guide/02-pawn-control/final/Commander
local t = game.test

t.describe("Commander", function()
  t.it("lines pawns up in a three wide block", function()
    local commander = game.interop.get("commander")
    local cells = commander.formation(10, 20, 5)
    t.expect(#cells).to_be(5)
    t.expect(cells[1]).to_equal({ x = 9, z = 20 })
    t.expect(cells[2]).to_equal({ x = 10, z = 20 })
    t.expect(cells[3]).to_equal({ x = 11, z = 20 })
    t.expect(cells[4]).to_equal({ x = 9, z = 21 })
  end)

  t.it("sends every selected pawn to a different cell", function()
    t.mock("input.mouse", { on_map = true, cell_x = 50, cell_z = 60 })
    t.mock("selection.pawns", { 11, 12, 13 })
    t.mock("job.go_to", true)
    t.mock("ui.translate", "ok")
    local commander = game.interop.get("commander")
    t.expect(commander.send_selected_to_mouse()).to_be(3)
    local calls = t.calls("job.go_to")
    t.expect(#calls).to_be(3)
    t.expect(calls[1].args.h).to_be(11)
    t.expect(calls[1].args.x).to_be(49)
    t.expect(calls[3].args.x).to_be(51)
  end)

  t.it("does nothing when the mouse is not over the map", function()
    t.mock("input.mouse", { on_map = false })
    t.expect(game.interop.get("commander").send_selected_to_mouse()).to_be(0)
    t.expect(#t.calls("job.go_to")).to_be(0)
  end)

  t.it("says so when nothing is selected", function()
    t.mock("input.mouse", { on_map = true, cell_x = 1, cell_z = 1 })
    t.mock("selection.pawns", {})
    t.mock("ui.translate", "Select a colonist first.")
    t.expect(game.interop.get("commander").send_selected_to_mouse()).to_be(0)
    t.expect(t.logged("Select a colonist")).to_be(true)
  end)

  t.it("toggles the draft of each selected pawn", function()
    t.mock("selection.pawns", { 4, 5 })
    t.mock("pawn.drafted", false)
    t.mock("pawn.set_drafted", true)
    t.expect(game.interop.get("commander").toggle_draft_selected()).to_be(2)
    t.expect(#t.calls("pawn.set_drafted")).to_be(2)
  end)
end)
